### ISSUE TITLE
service port should have a name

### ISSUE THREAD

**Issue by lance** [bucharest-gold/nodeshift#183]
Not sure if this is the responsibility of nodeshift or not. Perhaps the boosters' yaml just needs to be changed to include a name property. If one does not exist, openshift will display this warning on the Edit Route screen.

> Service nodejs-rest-http has a single, unnamed port. A route cannot specifically target an unnamed service port. If more service ports are added later, the route will also direct traffic to them.

By adding a name to the port we get rid of this warning e.g. 

```yml
apiVersion: v1
kind: Service
metadata:
  name: nodejs-rest-http
spec:
  ports:
    - name: http,
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

```
